# Generated by Django 3.0 on 2023-04-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiosteganography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomessage',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
