# Generated by Django 3.0 on 2023-04-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiosteganography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomessage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
