# Generated by Django 4.1.7 on 2023-04-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiosteganography', '0002_auto_20230405_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
