# Generated by Django 3.0 on 2023-04-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiosteganography', '0002_audiomessage_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiomessage',
            name='username',
        ),
        migrations.AlterField(
            model_name='audiomessage',
            name='message',
            field=models.TextField(max_length=10000),
        ),
    ]
