# Generated by Django 3.0 on 2023-04-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiosteganography', '0003_auto_20230402_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomessage',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
