# Generated by Django 3.0 on 2023-04-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiosteganography', '0004_auto_20230402_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiomessage',
            name='audio_file',
        ),
    ]
