# Generated by Django 3.0 on 2023-04-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiosteganography', '0005_remove_audiomessage_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomessage',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
