# Generated by Django 4.1.7 on 2023-04-04 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiosteganography', '0006_audiomessage_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomessage',
            name='audio_file',
            field=models.FileField(default=datetime.datetime(2023, 4, 4, 12, 4, 27, 357458, tzinfo=datetime.timezone.utc), upload_to='audio/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audiomessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
