# Generated by Django 4.1.7 on 2023-04-04 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audiosteganography', '0007_alter_audiomessage_audio_file_alter_audiomessage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomessage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
