# Generated by Django 3.0 on 2023-04-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textsteganography', '0002_alter_textmessage_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
